.Dd November 17, 2013
.Dt AED 1
.Os AED
.Sh NAME
.Nm aed
.Nd perform aes256-cbc encryption/decryption
.Sh SYNOPSIS
.Nm
.Op Fl deh
.Op Fl p Ar passphrase
.Op Fl s Ar salt
.Sh DESCRIPTION
The
.Nm
utility can be used to perform symmetric encryption/decryption of the
input stream using 256bit AES with a SHA1 digest.
.Sh OPTIONS
.Nm
supports the following command-line options:
.Bl -tag -width p_passphrase_
.It Fl d
Perform decryption of the input stream.
.It Fl e
Perform encryption of the input stream.
.It Fl h
Print a short usage and exit.
.It Fl p Ar passphrase
Use the given passphrase to derive the key.
.It Fl s Ar salt
Use the given salt.
If specified, then this needs to be exactly 8 hexadecimal characters.
.El
.Sh DETAILS
.Nm
reads data from stdin and either encrypts or decrypts it (depending on the
.Fl d
or
.Fl e
flag).
It uses AES 256bit CBC mode with a SHA1 digest with keying material
derived from the passphrase using the
.Xr EVP_BytesToKey 3
function.
.Pp
The passphrase may be specified via the
.Fl p
flag; if so,
.Nm
prevents leaking the data into the process table by using
.Xr setproctitle 3
(where available) or by manipulating \fBargv\fR.
.Pp
If the
.Fl p
flag was not specified, then
.Nm
will prompt the user for the passphrase on the controlling terminal.
When encrypting,
.Nm
will prompt the user twice to ensure the passphrase was entered correctly.
.Pp
If the
.Fl s
flag was not specified, then
.Nm
will not use a salt.
This is not recommended.
.Pp
Output is written to stdout.
.Sh EXAMPLES
The following examples show common usage.
.Pp
To encrypt the contents of the file 'file' using the passphrase 'm3i sup4h
s3cr3t'and storing the encrypted output in 'file.enc':
.Bd -literal -offset indent
aed -e -p 'm3i sup4h s3cr3t' <file >file.enc
.Ed
.Pp
To decrypt the contents of that file again:
.Bd -literal -offset indent
aed -d -p 'm3i sup4h s3cr3t' <file.enc
.Ed
.Pp
To encrypt and immediately decrypt the secret message, prompting the user for
the passphrase:
.Bd -literal -offset indent
echo "Kookaburra has left the tree" | aed -e | aed -d
.Ed
.Sh EXIT STATUS
.Nm
exits 0 on success, and >0 if an error occurred.
.Sh SEE ALSO
.Xr blowfish 3 ,
.Xr EVP_BytesToKey 3 ,
.Xr EVP_EncryptInit 3
.Sh HISTORY
This program (or variants thereof) was first assigned as a stand-alone
programming assignment for the class
.Dq Advanced Programming in the UNIX Environment
at Stevens Institute of Technology in the Fall of 2012.
.Sh BUGS
Well, let's see...
